name: my_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_form_builder: ^6.0.1
  flutter_map: any
  user_location:
    git:
      url: https://github.com/igaurab/user_location_plugin.git
  supabase: ^0.0.1-dev.17
  flutter_styled_toast: ^2.0.0
  shared_preferences: ^2.0.6
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  badges: ^2.0.1
  maps_toolkit: ^2.0.0
  postgrest: ^0.1.3
  postgres: 2.3.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  expandable: ^5.0.1
  internet_connection_checker: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/config.json

  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
